#!/usr/bin/env python3
"""Fase 8c/8d: Traduce strings PT-BR remanecentes en edge functions a es-PY.
Aplica reemplazos regex word-boundary (case-sensitive) sobre archivos .ts.
"""
import re, sys, pathlib

REPLACEMENTS = [
    # Pronombres / saludos
    (r'\bVocê\b', 'Usted'),
    (r'\bvocê\b', 'usted'),
    (r'\bOlá\b', 'Hola'),
    (r'\bolá\b', 'hola'),
    (r'\bObrigado\b', 'Gracias'),
    (r'\bobrigado\b', 'gracias'),
    (r'\bObrigada\b', 'Gracias'),
    (r'\bSeu\b', 'Su'),
    (r'\bseu\b', 'su'),
    (r'\bSua\b', 'Su'),
    (r'\bsua\b', 'su'),
    (r'\bSeus\b', 'Sus'),
    (r'\bseus\b', 'sus'),
    (r'\bSuas\b', 'Sus'),
    (r'\bsuas\b', 'sus'),
    # Negaciones / verbos comunes
    (r'\bNão\b', 'No'),
    (r'\bnão\b', 'no'),
    (r'\bSim\b', 'Sí'),
    (r'\bsim\b', 'sí'),
    (r'\bestá\b', 'está'),  # noop pero asegura unicode
    (r'\bsão\b', 'son'),
    (r'\bfoi\b', 'fue'),
    (r'\bsera\b', 'será'),
    (r'\bteve\b', 'tuvo'),
    (r'\btem\b', 'tiene'),
    (r'\bpode\b', 'puede'),
    (r'\bdeve\b', 'debe'),
    (r'\bfazer\b', 'hacer'),
    (r'\bcriar\b', 'crear'),
    (r'\bcriado\b', 'creado'),
    (r'\bcriada\b', 'creada'),
    (r'\benviar\b', 'enviar'),
    (r'\benviado\b', 'enviado'),
    (r'\benviada\b', 'enviada'),
    (r'\benviou\b', 'envió'),
    (r'\brecebido\b', 'recibido'),
    (r'\brecebida\b', 'recibida'),
    (r'\batualizar\b', 'actualizar'),
    (r'\batualizado\b', 'actualizado'),
    (r'\batualizada\b', 'actualizada'),
    (r'\bsalvar\b', 'guardar'),
    (r'\bsalvo\b', 'guardado'),
    (r'\bexcluir\b', 'eliminar'),
    (r'\bexcluído\b', 'eliminado'),
    (r'\bremover\b', 'eliminar'),
    (r'\bremovido\b', 'eliminado'),
    (r'\bbuscar\b', 'buscar'),
    (r'\bcarregar\b', 'cargar'),
    (r'\bcarregando\b', 'cargando'),
    (r'\bprocurar\b', 'buscar'),
    (r'\bfalhou\b', 'falló'),
    (r'\bfalha\b', 'falla'),
    (r'\bsucesso\b', 'éxito'),
    (r'\berro\b', 'error'),
    (r'\bErro\b', 'Error'),
    # Sustantivos comunes
    (r'\busuário\b', 'usuario'),
    (r'\busuários\b', 'usuarios'),
    (r'\bUsuário\b', 'Usuario'),
    (r'\btelefone\b', 'teléfono'),
    (r'\bTelefone\b', 'Teléfono'),
    (r'\bendereço\b', 'dirección'),
    (r'\bEndereço\b', 'Dirección'),
    (r'\bempresa\b', 'empresa'),
    (r'\bcliente\b', 'cliente'),
    (r'\bclientes\b', 'clientes'),
    (r'\bvenda\b', 'venta'),
    (r'\bvendas\b', 'ventas'),
    (r'\bproduto\b', 'producto'),
    (r'\bprodutos\b', 'productos'),
    (r'\bProduto\b', 'Producto'),
    (r'\bpedido\b', 'pedido'),
    (r'\bpedidos\b', 'pedidos'),
    (r'\bmensagem\b', 'mensaje'),
    (r'\bMensagem\b', 'Mensaje'),
    (r'\bmensagens\b', 'mensajes'),
    (r'\bconversa\b', 'conversación'),
    (r'\bconversas\b', 'conversaciones'),
    (r'\bConversa\b', 'Conversación'),
    (r'\batendimento\b', 'atención'),
    (r'\bAtendimento\b', 'Atención'),
    (r'\batendente\b', 'agente'),
    (r'\bvendedor\b', 'vendedor'),
    (r'\bvendedores\b', 'vendedores'),
    (r'\bequipe\b', 'equipo'),
    (r'\bEquipe\b', 'Equipo'),
    (r'\bsetor\b', 'sector'),
    (r'\bSetor\b', 'Sector'),
    (r'\bsenha\b', 'contraseña'),
    (r'\bSenha\b', 'Contraseña'),
    (r'\bconta\b', 'cuenta'),
    (r'\bConta\b', 'Cuenta'),
    (r'\bnome\b', 'nombre'),
    (r'\bNome\b', 'Nombre'),
    (r'\bsobrenome\b', 'apellido'),
    (r'\bdata\b', 'fecha'),
    (r'\bdatas\b', 'fechas'),
    (r'\bData\b', 'Fecha'),
    (r'\bhora\b', 'hora'),
    (r'\bhorário\b', 'horario'),
    (r'\bHorário\b', 'Horario'),
    (r'\bagendamento\b', 'reserva'),
    (r'\bAgendamento\b', 'Reserva'),
    (r'\bagendamentos\b', 'reservas'),
    (r'\breunião\b', 'reunión'),
    (r'\bReunião\b', 'Reunión'),
    (r'\bfunil\b', 'embudo'),
    (r'\bFunil\b', 'Embudo'),
    (r'\bfluxo\b', 'flujo'),
    (r'\bFluxo\b', 'Flujo'),
    (r'\bcampanha\b', 'campaña'),
    (r'\bCampanha\b', 'Campaña'),
    (r'\bcampanhas\b', 'campañas'),
    (r'\btarefa\b', 'tarea'),
    (r'\bTarefa\b', 'Tarea'),
    (r'\btarefas\b', 'tareas'),
    (r'\bobservação\b', 'observación'),
    (r'\bObservação\b', 'Observación'),
    (r'\bobservações\b', 'observaciones'),
    (r'\bconfiguração\b', 'configuración'),
    (r'\bConfiguração\b', 'Configuración'),
    (r'\bconfigurações\b', 'configuraciones'),
    (r'\binformação\b', 'información'),
    (r'\bInformação\b', 'Información'),
    (r'\binformações\b', 'información'),
    (r'\bIntegração\b', 'Integración'),
    (r'\bintegração\b', 'integración'),
    (r'\bintegrações\b', 'integraciones'),
    (r'\bnotificação\b', 'notificación'),
    (r'\bnotificações\b', 'notificaciones'),
    (r'\bNotificação\b', 'Notificación'),
    (r'\baplicação\b', 'aplicación'),
    (r'\bações\b', 'acciones'),
    (r'\bação\b', 'acción'),
    (r'\bAção\b', 'Acción'),
    (r'\bopção\b', 'opción'),
    (r'\bopções\b', 'opciones'),
    (r'\bOpção\b', 'Opción'),
    (r'\bdescrição\b', 'descripción'),
    (r'\bDescrição\b', 'Descripción'),
    (r'\bsituação\b', 'situación'),
    (r'\bdúvida\b', 'duda'),
    (r'\bdúvidas\b', 'dudas'),
    (r'\bnúmero\b', 'número'),
    (r'\bNúmero\b', 'Número'),
    (r'\bdocumento\b', 'documento'),
    (r'\bDocumento\b', 'Documento'),
    (r'\barquivo\b', 'archivo'),
    (r'\barquivos\b', 'archivos'),
    (r'\bArquivo\b', 'Archivo'),
    (r'\bimagem\b', 'imagen'),
    (r'\bImagem\b', 'Imagen'),
    (r'\bdinheiro\b', 'dinero'),
    (r'\bvalor\b', 'valor'),
    (r'\bvalores\b', 'valores'),
    (r'\bpagamento\b', 'pago'),
    (r'\bpagamentos\b', 'pagos'),
    (r'\bPagamento\b', 'Pago'),
    (r'\bdesconto\b', 'descuento'),
    (r'\bparcela\b', 'cuota'),
    (r'\bparcelas\b', 'cuotas'),
    (r'\bcartão\b', 'tarjeta'),
    (r'\bCartão\b', 'Tarjeta'),
    (r'\bboleto\b', 'boleto'),
    (r'\bnegócio\b', 'negocio'),
    (r'\bnegócios\b', 'negocios'),
    (r'\bNegócio\b', 'Negocio'),
    (r'\boportunidade\b', 'oportunidad'),
    (r'\boportunidades\b', 'oportunidades'),
    (r'\bcalendário\b', 'calendario'),
    (r'\bCalendário\b', 'Calendario'),
    (r'\bsemana\b', 'semana'),
    (r'\bmês\b', 'mes'),
    (r'\bmeses\b', 'meses'),
    (r'\bdia\b', 'día'),
    (r'\bdias\b', 'días'),
    (r'\bhoje\b', 'hoy'),
    (r'\bontem\b', 'ayer'),
    (r'\bamanhã\b', 'mañana'),
    (r'\bagora\b', 'ahora'),
    (r'\bdepois\b', 'después'),
    (r'\bantes\b', 'antes'),
    (r'\bsempre\b', 'siempre'),
    (r'\bnunca\b', 'nunca'),
    (r'\bmuito\b', 'mucho'),
    (r'\bpouco\b', 'poco'),
    (r'\btodos\b', 'todos'),
    (r'\btodas\b', 'todas'),
    (r'\balgum\b', 'algún'),
    (r'\balguma\b', 'alguna'),
    (r'\bnenhum\b', 'ningún'),
    (r'\bnenhuma\b', 'ninguna'),
    (r'\boutro\b', 'otro'),
    (r'\boutra\b', 'otra'),
    (r'\bmesmo\b', 'mismo'),
    (r'\bmesma\b', 'misma'),
    # Frases comunes
    (r'\bnão foi possível\b', 'no fue posible'),
    (r'\bNão foi possível\b', 'No fue posible'),
    (r'\bnão encontrado\b', 'no encontrado'),
    (r'\bNão encontrado\b', 'No encontrado'),
    (r'\bnão encontrada\b', 'no encontrada'),
    (r'\bem português\b', 'en español'),
    (r'\bportuguês\b', 'español'),
    (r'\bPortuguês\b', 'Español'),
    (r'\bportuguesa\b', 'española'),
    (r'\bportuguesas\b', 'españolas'),
    (r'\bcom sucesso\b', 'con éxito'),
    (r'\bao salvar\b', 'al guardar'),
    (r'\bao criar\b', 'al crear'),
    (r'\bao atualizar\b', 'al actualizar'),
    (r'\bao excluir\b', 'al eliminar'),
    (r'\bao enviar\b', 'al enviar'),
    (r'\bao carregar\b', 'al cargar'),
    (r'\bao buscar\b', 'al buscar'),
    (r'\bpor favor\b', 'por favor'),
    (r'\bPor favor\b', 'Por favor'),
    (r'\bque você\b', 'que usted'),
    (r'\bque o cliente\b', 'que el cliente'),
    (r'\bdo cliente\b', 'del cliente'),
    (r'\bda empresa\b', 'de la empresa'),
    (r'\bda equipe\b', 'del equipo'),
    (r'\bdo produto\b', 'del producto'),
    (r'\bdo lead\b', 'del lead'),
    (r'\bdo agente\b', 'del agente'),
    (r'\bdo usuário\b', 'del usuario'),
    (r'\bao agente\b', 'al agente'),
    (r'\bao cliente\b', 'al cliente'),
    (r'\bao usuário\b', 'al usuario'),
    (r'\bao lead\b', 'al lead'),
    (r'\bpara o cliente\b', 'para el cliente'),
    (r'\bpara o lead\b', 'para el lead'),
    (r'\bpara o usuário\b', 'para el usuario'),
    (r'\bpara o agente\b', 'para el agente'),
    (r'\bResponda em\b', 'Responde en'),
    (r'\bResponda sempre\b', 'Responde siempre'),
    (r'\bResponda apenas\b', 'Responde solo'),
    (r'\bRetorne apenas\b', 'Devuelve solo'),
    (r'\bRetorne em\b', 'Devuelve en'),
    (r'\bRetorne um\b', 'Devuelve un'),
    (r'\bRetorne uma\b', 'Devuelve una'),
    (r'\bGere\b', 'Genera'),
    (r'\bCrie\b', 'Crea'),
    (r'\bEscreva\b', 'Escribe'),
    (r'\bAnalise\b', 'Analiza'),
    (r'\bIdentifique\b', 'Identifica'),
    (r'\bSugira\b', 'Sugiere'),
    (r'\bClassifique\b', 'Clasifica'),
    (r'\bExplique\b', 'Explica'),
    (r'\bConsidere\b', 'Considera'),
    (r'\bUtilize\b', 'Utiliza'),
    (r'\bUse\b', 'Usa'),
    (r'\bSiga\b', 'Sigue'),
    (r'\bEvite\b', 'Evita'),
    (r'\bSeja\b', 'Sé'),
    (r'\bobjetivo\b', 'objetivo'),
    (r'\bobjetiva\b', 'objetiva'),
    (r'\bcurta\b', 'corta'),
    (r'\bcurto\b', 'corto'),
    (r'\blonga\b', 'larga'),
    (r'\blongo\b', 'largo'),
    (r'\bperguntas\b', 'preguntas'),
    (r'\bpergunta\b', 'pregunta'),
    (r'\brespostas\b', 'respuestas'),
    (r'\bresposta\b', 'respuesta'),
    (r'\bresumo\b', 'resumen'),
    (r'\bResumo\b', 'Resumen'),
    (r'\binício\b', 'inicio'),
    (r'\bInício\b', 'Inicio'),
    (r'\bfim\b', 'fin'),
    (r'\bFim\b', 'Fin'),
    (r'\bduração\b', 'duración'),
    (r'\bDuração\b', 'Duración'),
    (r'\binválido\b', 'inválido'),
    (r'\binválida\b', 'inválida'),
    (r'\bobrigatório\b', 'obligatorio'),
    (r'\bobrigatória\b', 'obligatoria'),
    (r'\bopcional\b', 'opcional'),
    (r'\bpermitido\b', 'permitido'),
    (r'\bproibido\b', 'prohibido'),
    (r'\bpermissão\b', 'permiso'),
    (r'\bpermissões\b', 'permisos'),
]

# Compile
patterns = [(re.compile(p), r) for p, r in REPLACEMENTS]

def translate_file(path: pathlib.Path) -> bool:
    try:
        text = path.read_text(encoding='utf-8')
    except Exception:
        return False
    orig = text
    for pat, repl in patterns:
        text = pat.sub(repl, text)
    if text != orig:
        path.write_text(text, encoding='utf-8')
        return True
    return False

def main():
    root = pathlib.Path('supabase/functions')
    count = 0
    for p in root.rglob('*.ts'):
        # Skip already-Spanish shared template files we curated by hand
        skip = ('email-templates', 'transactional-email-templates',
                'agent-prompt-templates', 'booking-templates', 'quick-menu')
        if any(s in str(p) for s in skip):
            continue
        if translate_file(p):
            count += 1
            print(f"  edit: {p}")
    print(f"\nTotal: {count} archivos")

if __name__ == '__main__':
    main()
