#!/usr/bin/env python3
"""Phase 9c: Aggressive PT->ES translation of remaining prompts in edge functions."""
import os, re, sys

ROOT = "supabase/functions"

# Order matters: longer/more specific first
PAIRS = [
    # Headers/sections
    ("EXECUTIVE_KERNEL (regras imutáveis – sobrescrevem qualquer modificador)", "EXECUTIVE_KERNEL (reglas inmutables – sobrescriben cualquier modificador)"),
    ("QUEM VOCÊ É", "QUIÉN SOS"),
    ("COM QUEM VOCÊ FALA", "CON QUIÉN HABLÁS"),
    ("CONTEXTO DA EMPRESA", "CONTEXTO DE LA EMPRESA"),
    ("O QUE VOCÊ NUNCA FAZ", "LO QUE NUNCA HACÉS"),
    ("O QUE VOCÊ SEMPRE FAZ", "LO QUE SIEMPRE HACÉS"),
    ("SAUDAÇÃO PADRÃO", "SALUDO ESTÁNDAR"),
    ("MEMÓRIA E CONTINUIDADE", "MEMORIA Y CONTINUIDAD"),
    ("regras absolutas", "reglas absolutas"),
    ("apenas na PRIMEIRA mensagem da conversação", "solo en el PRIMER mensaje de la conversación"),
    # Roles / pronouns
    ("braço-direito executivo", "mano derecha ejecutiva"),
    ("Chief of Staff", "Chief of Staff"),
    ("**assessor interno**", "**asesor interno**"),
    ("dados operacionais", "datos operativos"),
    ("seu chefe direto", "tu jefe directo"),
    ("seu chefe", "tu jefe"),
    ("dele(a)", "de él/ella"),
    ("está cadastrado como admin no sistema", "está registrado como admin en el sistema"),
    ("Trate-o(a) como gestor da casa", "Tratalo/a como gestor de la casa"),
    # Bullet content
    ("tenta agendar reunião com", "intenta agendar reunión con"),
    ("ele é su chefe, no um lead", "él/ella es tu jefe, no un lead"),
    ("pergunta", "pregunta"),
    ("como posso te auxiliar com", "cómo puedo ayudarte con"),
    ("tiene interesse em", "tiene interés en"),
    ("usa pitch comercial", "uses pitch comercial"),
    ("implementação", "implementación"),
    ("jornada", "recorrido"),
    ("vamos avançar", "vamos a avanzar"),
    ("qualificação", "calificación"),
    ("pede nombre, teléfono, email, segmento", "pide nombre, teléfono, email, segmento"),
    ("usted já sabe quem ele é", "vos ya sabés quién es"),
    ("trata o admin como lead ou prospecto", "tratás al admin como lead o prospecto"),
    ("cria, edita, move ou apaga dados", "creés, editás, movés o borrás datos"),
    ("SOMENTE-LEITURA", "SOLO-LECTURA"),
    ("Se pedirem acción de escrita", "Si te piden acción de escritura"),
    ("Sou somente-leitura. Usa o painel para esta acción", "Soy solo-lectura. Usá el panel para esta acción"),
    # Always-do block
    ("Antes de responder qualquer pergunta sobre dados", "Antes de responder cualquier pregunta sobre datos"),
    ("USA uma tool. Sem chutes", "USÁ una tool. Sin adivinar"),
    ("Se o admin pedir", "Si el admin pide"),
    ("como está hoy", "cómo está hoy"),
    ("situação", "situación"),
    ("PRIMEIRO. Nunca pergunte", "PRIMERO. Nunca preguntes"),
    ("qual resumen", "cuál resumen"),
    ("Tem reserva hoy?", "¿Hay reservas hoy?"),
    ("Reuniões hoy?", "¿Reuniones hoy?"),
    ("consulta a agenda DA EQUIPE", "consulta la agenda DEL EQUIPO"),
    ("no tenta marcar reunión com usted", "no intentes marcar reunión con vos"),
    ("Cómo está [nombre de vendedor]?", "¿Cómo está [nombre de vendedor]?"),
    ("responda só sobre essa pessoa", "respondé solo sobre esa persona"),
    ("embudo / negocios", "embudo / negocios"),
    ("Inbox / atención / sem respuesta", "Inbox / atención / sin respuesta"),
    ("Comissão / receita / financeiro", "Comisión / ingresos / financiero"),
    ("Metas / progresso", "Metas / progreso"),
    ("Tarefas / pendências", "Tareas / pendientes"),
    ("Erros / agentes / IA", "Errores / agentes / IA"),
    ("Se a pregunta for vaga, escolha a tool mais provável", "Si la pregunta es vaga, elegí la tool más probable"),
    ("mostre o resultado – después oferezca", "mostrá el resultado – después ofrecé"),
    ("quiere ver mais detalhes?", "¿querés ver más detalles?"),
    # Saudação
    ("Se ${adminName} disser \"oi\", \"hola\", \"qual su nombre\", \"tudo bem\"", "Si ${adminName} dice \"hola\", \"qué tal\", \"cuál es tu nombre\", \"cómo va\""),
    ("aún no houver histórico de mensajes sus nestla conversación", "aún no hay historial de mensajes en esta conversación"),
    ("Sou a *${agentName}*, su Chief of Staff. Pode me perguntar sobre pipeline, equipo, agenda, financiero, metas o alertas.", "Soy *${agentName}*, tu Chief of Staff. Podés preguntarme sobre pipeline, equipo, agenda, financiero, metas o alertas."),
    ("NADA além disso. Sem oferecer producto, sem perguntar interesse, sem pitch", "NADA más que eso. Sin ofrecer producto, sin preguntar interés, sin pitch"),
    # Memory
    ("CRÍTICO", "CRÍTICO"),
    ("Usted TEM acesso ao histórico desta conversación", "Tenés acceso al historial de esta conversación"),
    ("mensajes anteriores aparecem antes da atual", "los mensajes anteriores aparecen antes del actual"),
    ("**NUNCA repita uma pregunta que usted ya fez", "**NUNCA repitas una pregunta que ya hiciste"),
    ("Se ya oferec", "Si ya ofreciste"),
    ("quiere briefing, pipeline ou financiero", "querés briefing, pipeline o financiero"),
    ("no oferezca de novo", "no lo ofrezcas de nuevo"),
    ("**NUNCA repita a saudação", "**NUNCA repitas el saludo"),
    ("se usted ya falou nestla conversación", "si ya hablaste en esta conversación"),
    ("Vá direto à información", "Andá directo a la información"),
    # Generic high-frequency residuals
    ("nestla", "en esta"),
    ("nesta", "en esta"),
    ("neste", "en este"),
    ("nessa", "en esa"),
    ("nesse", "en ese"),
    ("conversação", "conversación"),
    ("você", "vos"),
    ("Você", "Vos"),
    ("VOCÊ", "VOS"),
    ("alertas.\"", "alertas.\""),
    ("Pode me", "Podés"),
    ("perguntar", "preguntar"),
    ("Sem chutes", "Sin adivinar"),
    ("Sem ofererecer", "Sin ofrecer"),
    ("oferecer", "ofrecer"),
    ("ofererecer", "ofrecer"),
    ("oferec", "ofrec"),
    ("histórico", "historial"),
    ("memória", "memoria"),
    ("saudação", "saludo"),
    ("padrão", "estándar"),
    ("pergunte", "preguntes"),
    ("pergunta", "pregunta"),
    ("pendências", "pendientes"),
    ("tarefas", "tareas"),
    ("Tarefas", "Tareas"),
    ("metas", "metas"),
    ("comissão", "comisión"),
    ("Comissão", "Comisión"),
    ("receita", "ingresos"),
    ("financeiro", "financiero"),
    ("progresso", "progreso"),
    ("erros", "errores"),
    ("Erros", "Errores"),
    ("reuniões", "reuniones"),
    ("Reuniões", "Reuniones"),
    ("reunião", "reunión"),
    ("agenda DA EQUIPE", "agenda DEL EQUIPO"),
    ("hoy", "hoy"),  # ok already
    ("amanhã", "mañana"),
    ("ontem", "ayer"),
    ("disser", "dice"),
    ("tudo bem", "todo bien"),
    ("qual su nombre", "cuál es tu nombre"),
    ("escolha", "elegí"),
    ("mais provável", "más probable"),
    ("mostre", "mostrá"),
    ("resultado – después", "resultado – después"),
    ("após", "después"),
    ("apenas", "solo"),
    ("ainda no", "todavía no"),
    ("aún no", "aún no"),
    ("houver", "hay"),
    ("além disso", "más allá de eso"),
    ("ningún humano registrado", "ningún humano registrado"),
    ("ningún agente IA configurado", "ningún agente IA configurado"),
    ("vendedor", "vendedor"),
    ("chefe", "jefe"),
    ("dono", "dueño"),
    ("regras imutáveis", "reglas inmutables"),
    ("sobrescrevem", "sobrescriben"),
    ("qualquer modificador", "cualquier modificador"),
    ("cliente.", "cliente."),
    ("prospect", "prospecto"),
    ("painel", "panel"),
    ("acción de escrita", "acción de escritura"),
    ("Somente-leitura", "Solo-lectura"),
    ("somente-leitura", "solo-lectura"),
    ("imutáveis", "inmutables"),
    ("registrado como admin no sistema", "registrado como admin en el sistema"),
    # Common verbs/forms
    (" é ", " es "),
    (" são ", " son "),
    (" está ", " está "),
    (" não ", " no "),
    (" sim ", " sí "),
    (" também ", " también "),
    (" porém ", " pero "),
    (" então ", " entonces "),
    (" sem ", " sin "),
    (" com ", " con "),
    (" para ", " para "),
    (" pelo ", " por el "),
    (" pela ", " por la "),
    (" pelos ", " por los "),
    (" pelas ", " por las "),
    (" dele ", " de él "),
    (" dela ", " de ella "),
    (" deles ", " de ellos "),
    (" delas ", " de ellas "),
    (" desse ", " de ese "),
    (" dessa ", " de esa "),
    (" desses ", " de esos "),
    (" dessas ", " de esas "),
    (" deste ", " de este "),
    (" desta ", " de esta "),
    (" daqui ", " de aquí "),
    (" daí ", " de ahí "),
    (" lá ", " allá "),
    (" aqui ", " aquí "),
    (" aí ", " ahí "),
    (" muito ", " mucho "),
    (" pouco ", " poco "),
    (" bom ", " bueno "),
    (" boa ", " buena "),
    (" bem ", " bien "),
    (" mal ", " mal "),
    (" hoje ", " hoy "),
    (" agora ", " ahora "),
    (" depois ", " después "),
    (" antes ", " antes "),
    (" sempre ", " siempre "),
    (" nunca ", " nunca "),
    (" cada ", " cada "),
    (" algum ", " algún "),
    (" alguma ", " alguna "),
    (" alguns ", " algunos "),
    (" algumas ", " algunas "),
    (" outro ", " otro "),
    (" outra ", " otra "),
    (" outros ", " otros "),
    (" outras ", " otras "),
    (" tudo ", " todo "),
    (" toda ", " toda "),
    (" todos ", " todos "),
    (" todas ", " todas "),
    (" enquanto ", " mientras "),
    (" embora ", " aunque "),
    (" porque ", " porque "),
    (" por que ", " por qué "),
    (" quando ", " cuando "),
    (" onde ", " donde "),
    (" como ", " como "),
    (" quem ", " quién "),
    (" qual ", " cuál "),
    (" quais ", " cuáles "),
    (" quanto ", " cuánto "),
    (" quantos ", " cuántos "),
    # Fix double-translation artifacts
    ("vossvos", "vos"),
    ("vosos", "vos"),
    ("ess es", "eso es"),
    ("lla ", "la "),
    (" lla", " la"),
]

def translate(text):
    for old, new in PAIRS:
        text = text.replace(old, new)
    return text

def should_skip(path):
    # Skip non-code
    return False

count_changed = 0
count_total = 0
for dirpath, _, files in os.walk(ROOT):
    for f in files:
        if not (f.endswith(".ts") or f.endswith(".tsx")):
            continue
        p = os.path.join(dirpath, f)
        count_total += 1
        try:
            with open(p, "r", encoding="utf-8") as fp:
                orig = fp.read()
        except Exception:
            continue
        new = translate(orig)
        if new != orig:
            with open(p, "w", encoding="utf-8") as fp:
                fp.write(new)
            count_changed += 1

print(f"Translated {count_changed}/{count_total} files")
