#!/usr/bin/env python3
"""Fase 9: Traduce contenido seed (DB seeds .sql) y residuos PT-BR
en frontend (src/components/admin/{capture,agents,...}) a es-PY."""
import re, sys, pathlib

# Reusa los patrones de phase 8
sys.path.insert(0, '.')
from translate_phase8 import patterns as P8

EXTRA = [
    # Pipeline/sales stages
    (r'\bQualificação\b', 'Calificación'),
    (r'\bqualificação\b', 'calificación'),
    (r'\bQualificar\b', 'Calificar'),
    (r'\bqualificar\b', 'calificar'),
    (r'\bQualificado\b', 'Calificado'),
    (r'\bqualificado\b', 'calificado'),
    (r'\bQualificada\b', 'Calificada'),
    (r'\bQualificador\b', 'Calificador'),
    (r'\bProspecção\b', 'Prospección'),
    (r'\bprospecção\b', 'prospección'),
    (r'\bNegociação\b', 'Negociación'),
    (r'\bnegociação\b', 'negociación'),
    (r'\bProposta\b', 'Propuesta'),
    (r'\bproposta\b', 'propuesta'),
    (r'\bPropostas\b', 'Propuestas'),
    (r'\bGanho\b', 'Ganado'),
    (r'\bganho\b', 'ganado'),
    (r'\bPerdido\b', 'Perdido'),
    (r'\bFechado\b', 'Cerrado'),
    (r'\bfechado\b', 'cerrado'),
    (r'\bFechamento\b', 'Cierre'),
    (r'\bfechamento\b', 'cierre'),
    (r'\bAbertura\b', 'Apertura'),
    (r'\bAbordagem\b', 'Abordaje'),
    (r'\babordagem\b', 'abordaje'),
    (r'\bFunil de Qualificação\b', 'Embudo de Calificación'),
    (r'\bFluxo de Qualificação\b', 'Flujo de Calificación'),
    # Tag package
    (r'\bPIX Gerado\b', 'PIX Generado'),
    (r'\bBoleto Gerado\b', 'Boleto Generado'),
    (r'\bAguardando Pagamento\b', 'Esperando Pago'),
    (r'\bCheckout Abandonado\b', 'Checkout Abandonado'),
    (r'\bReembolso\b', 'Reembolso'),
    # Seeds PT-BR phrases (help/release)
    (r'\bPrimeiros passos\b', 'Primeros pasos'),
    (r'\bprimeiros-passos\b', 'primeros-pasos'),
    (r'\bVendas e Pipeline\b', 'Ventas y Pipeline'),
    (r'\bvendas-pipeline\b', 'ventas-pipeline'),
    (r'\bAtendimento e Inbox\b', 'Atención e Inbox'),
    (r'\batendimento-inbox\b', 'atencion-inbox'),
    (r'\bIA e Automação\b', 'IA y Automatización'),
    (r'\bia-automacao\b', 'ia-automatizacion'),
    (r'\bIntegrações\b', 'Integraciones'),
    (r'\bintegracoes\b', 'integraciones'),
    (r'\bAdministração\b', 'Administración'),
    (r'\badministracao\b', 'administracion'),
    (r'\bCentral de Ajuda\b', 'Centro de Ayuda'),
    (r'\bcentral de ajuda\b', 'centro de ayuda'),
    (r'\bAjuda\b', 'Ayuda'),
    (r'\bajuda\b', 'ayuda'),
    # Common admin/agents/capture phrases
    (r'\bSequência\b', 'Secuencia'),
    (r'\bsequência\b', 'secuencia'),
    (r'\bautomação\b', 'automatización'),
    (r'\bAutomação\b', 'Automatización'),
    (r'\bautomações\b', 'automatizaciones'),
    (r'\bAutomações\b', 'Automatizaciones'),
    (r'\bautomática\b', 'automática'),
    (r'\bautomático\b', 'automático'),
    (r'\bobrigatórios\b', 'obligatorios'),
    (r'\bobrigatórias\b', 'obligatorias'),
    (r'\baprovação\b', 'aprobación'),
    (r'\bAprovação\b', 'Aprobación'),
    (r'\baprovado\b', 'aprobado'),
    (r'\baprovada\b', 'aprobada'),
    (r'\baprovou\b', 'aprobó'),
    (r'\baplicação\b', 'aplicación'),
    (r'\bAplicação\b', 'Aplicación'),
    (r'\baplicações\b', 'aplicaciones'),
    (r'\bcontato\b', 'contacto'),
    (r'\bContato\b', 'Contacto'),
    (r'\bcontatos\b', 'contactos'),
    (r'\bbreve\b', 'breve'),
    (r'\bbem-vindo\b', 'bienvenido'),
    (r'\bBem-vindo\b', 'Bienvenido'),
    (r'\bbem-vinda\b', 'bienvenida'),
    (r'\bBem-vinda\b', 'Bienvenida'),
    (r'\bnovidades\b', 'novedades'),
    (r'\bNovidades\b', 'Novedades'),
    (r'\bMelhorias\b', 'Mejoras'),
    (r'\bmelhorias\b', 'mejoras'),
    (r'\bcorreções\b', 'correcciones'),
    (r'\bCorreções\b', 'Correcciones'),
    (r'\bAtualizações\b', 'Actualizaciones'),
    (r'\batualizações\b', 'actualizaciones'),
    (r'\blançamentos\b', 'lanzamientos'),
    (r'\bLançamento\b', 'Lanzamiento'),
    (r'\blançamento\b', 'lanzamiento'),
    (r'\brecurso\b', 'recurso'),
    (r'\brecursos\b', 'recursos'),
    (r'\bsobre\b', 'sobre'),
    (r'\bpermite\b', 'permite'),
    (r'\bpermitem\b', 'permiten'),
    (r'\bnecessidades\b', 'necesidades'),
    (r'\bnecessidade\b', 'necesidad'),
    (r'\bdesafio\b', 'desafío'),
    (r'\bdesafios\b', 'desafíos'),
    (r'\borçamento\b', 'presupuesto'),
    (r'\bOrçamento\b', 'Presupuesto'),
    (r'\binvestir\b', 'invertir'),
    (r'\bsolução\b', 'solución'),
    (r'\bSolução\b', 'Solución'),
    (r'\bsoluções\b', 'soluciones'),
    (r'\bespecialista\b', 'especialista'),
    (r'\bentrará\b', 'se pondrá'),
    (r'\bem contato\b', 'en contacto'),
    (r'\bem até\b', 'en hasta'),
    (r'\bMinimalista\b', 'Minimalista'),
    (r'\bsimples\b', 'simple'),
    (r'\bcompleto\b', 'completo'),
    (r'\bcompleta\b', 'completa'),
    (r'\brapidamente\b', 'rápidamente'),
    (r'\brápido\b', 'rápido'),
    (r'\brápida\b', 'rápida'),
    (r'\bprofundamente\b', 'profundamente'),
    (r'\bpoucos minutos\b', 'pocos minutos'),
    (r'\bDigite seu nome\b', 'Escribí tu nombre'),
    (r'\bDigite seu\b', 'Escribí tu'),
    (r'\bDigite\b', 'Escribí'),
    (r'\bResponda\b', 'Respondé'),
    (r'\bEnvie\b', 'Enviá'),
    (r'\bEnviar\b', 'Enviar'),
    (r'\bClique\b', 'Hacé clic'),
    (r'\bSelecione\b', 'Seleccioná'),
    (r'\bEscolha\b', 'Elegí'),
    (r'\bEscolher\b', 'Elegir'),
    (r'\bEscolhido\b', 'Elegido'),
    (r'\bMostrar\b', 'Mostrar'),
    (r'\bOcultar\b', 'Ocultar'),
    (r'\bExibir\b', 'Mostrar'),
    (r'\bvisualizar\b', 'visualizar'),
    (r'\bdiagnóstico\b', 'diagnóstico'),
    (r'\bDiagnóstico\b', 'Diagnóstico'),
    (r'\bDiagnóstico Completo\b', 'Diagnóstico Completo'),
    (r'\bDiagnóstico recebido\b', 'Diagnóstico recibido'),
    (r'\bCaptação\b', 'Captación'),
    (r'\bcaptação\b', 'captación'),
    (r'\bCaptação Simples\b', 'Captación Simple'),
    (r'\bCaptura\b', 'Captura'),
    (r'\bAprimorado\b', 'Mejorado'),
    (r'\baprimorado\b', 'mejorado'),
    (r'\baprimorando\b', 'mejorando'),
    (r'\bsendo aprimorado\b', 'siendo mejorado'),
    (r'\bestá sendo aprimorado\b', 'está siendo mejorado'),
    (r'\bvocê precisa\b', 'necesitás'),
    (r'\bVocê precisa\b', 'Necesitás'),
    (r'\bvocê tem\b', 'tenés'),
    (r'\bVocê tem\b', '¿Tenés'),
    (r'\bvocê pode\b', 'podés'),
    (r'\bVocê pode\b', 'Podés'),
    (r'\bvocê encontra\b', 'encontrás'),
    (r'\bquem faz o quê\b', 'quién hace qué'),
    (r'\bo que cada\b', 'qué hace cada'),
    (r'\bpapel pode acessar\b', 'rol puede acceder'),
    (r'\bhierarquia\b', 'jerarquía'),
    (r'\bResponsabilidades\b', 'Responsabilidades'),
    (r'\bresponsabilidades\b', 'responsabilidades'),
    (r'\bresponsabilidade\b', 'responsabilidad'),
    (r'\bgerenciar\b', 'gestionar'),
    (r'\bGerenciar\b', 'Gestionar'),
    (r'\bgerencia\b', 'gestiona'),
    (r'\bgerenciamento\b', 'gestión'),
    (r'\bgestão\b', 'gestión'),
    (r'\bGestão\b', 'Gestión'),
    (r'\borganização\b', 'organización'),
    (r'\bOrganização\b', 'Organización'),
    (r'\borganizações\b', 'organizaciones'),
    (r'\bidentidade visual\b', 'identidad visual'),
    (r'\bcontroles globais\b', 'controles globales'),
    (r'\binfraestrutura\b', 'infraestructura'),
    (r'\bplano\b', 'plan'),
    (r'\bplanos\b', 'planes'),
    (r'\bcondiç\b', 'condic'),
    (r'\bcondições\b', 'condiciones'),
    (r'\bcondição\b', 'condición'),
    (r'\bemissão\b', 'emisión'),
    (r'\bsubindo\b', 'subiendo'),
    (r'\bSubindo\b', 'Subiendo'),
    (r'\benviando\b', 'enviando'),
    (r'\bbaixar\b', 'descargar'),
    (r'\bBaixar\b', 'Descargar'),
    (r'\bdistribuição\b', 'distribución'),
    (r'\bDistribuição\b', 'Distribución'),
    (r'\bcomissão\b', 'comisión'),
    (r'\bComissão\b', 'Comisión'),
    (r'\bcomissões\b', 'comisiones'),
    (r'\bComissões\b', 'Comisiones'),
    (r'\bcobrança\b', 'cobro'),
    (r'\bCobrança\b', 'Cobro'),
    (r'\bcobranças\b', 'cobros'),
    (r'\bcobrar\b', 'cobrar'),
    (r'\binadimplência\b', 'morosidad'),
    (r'\bbom día\b', 'buen día'),
    (r'\bBom día\b', 'Buen día'),
    (r'\bboa tarde\b', 'buenas tardes'),
    (r'\bBoa tarde\b', 'Buenas tardes'),
    (r'\bboa noite\b', 'buenas noches'),
    (r'\bBoa noite\b', 'Buenas noches'),
    (r'\bjá\b', 'ya'),
    (r'\bJá\b', 'Ya'),
    (r'\bainda\b', 'aún'),
    (r'\bporém\b', 'pero'),
    (r'\btambém\b', 'también'),
    (r'\bTambém\b', 'También'),
    (r'\bcomo\b', 'como'),
    (r'\bquando\b', 'cuando'),
    (r'\bonde\b', 'dónde'),
    (r'\bporque\b', 'porque'),
    (r'\bpor que\b', 'por qué'),
    (r'\bpara que\b', 'para que'),
    (r'\bse necessário\b', 'si es necesario'),
    (r'\bse precisar\b', 'si es necesario'),
    (r'\bdeseja\b', 'desea'),
    (r'\bdesejar\b', 'desear'),
    (r'\bdesejado\b', 'deseado'),
    (r'\bquero\b', 'quiero'),
    (r'\bquer\b', 'quiere'),
    (r'\bquerer\b', 'querer'),
    (r'\bquerendo\b', 'queriendo'),
    (r'\btentar\b', 'intentar'),
    (r'\bTentar\b', 'Intentar'),
    (r'\btentativa\b', 'intento'),
    (r'\btentativas\b', 'intentos'),
    (r'\bcomeçar\b', 'comenzar'),
    (r'\bComeçar\b', 'Comenzar'),
    (r'\bcomeço\b', 'comienzo'),
    (r'\biniciar\b', 'iniciar'),
    (r'\bIniciar\b', 'Iniciar'),
    (r'\binicio\b', 'inicio'),
    (r'\bfinalizar\b', 'finalizar'),
    (r'\bFinalizar\b', 'Finalizar'),
    (r'\bencerrar\b', 'cerrar'),
    (r'\bEncerrar\b', 'Cerrar'),
    (r'\bAprenda\b', 'Aprendé'),
    (r'\baprenda\b', 'aprendé'),
    (r'\bAprender\b', 'Aprender'),
    (r'\baprender\b', 'aprender'),
    (r'\bSaiba\b', 'Sabé'),
    (r'\bsaiba\b', 'sabé'),
    (r'\bDescubra\b', 'Descubrí'),
    (r'\bdescubra\b', 'descubrí'),
    (r'\bConheça\b', 'Conocé'),
    (r'\bconheça\b', 'conocé'),
    (r'\bEntenda\b', 'Entendé'),
    (r'\bentenda\b', 'entendé'),
    (r'\bExperimente\b', 'Probá'),
    (r'\bexperimente\b', 'probá'),
    (r'\bRoteiro\b', 'Guión'),
    (r'\broteiro\b', 'guión'),
    (r'\bcadência\b', 'cadencia'),
    (r'\bCadência\b', 'Cadencia'),
    (r'\bcadências\b', 'cadencias'),
    (r'\bPlaybook\b', 'Playbook'),
    (r'\bToque\b', 'Toque'),
    (r'\btoque\b', 'toque'),
    (r'\btoques\b', 'toques'),
    (r'\bmaterial\b', 'material'),
    (r'\bMateriais\b', 'Materiales'),
    (r'\bmateriais\b', 'materiales'),
    (r'\bCentralize\b', 'Centralizá'),
    (r'\bcentralize\b', 'centralizá'),
    (r'\btime\b', 'equipo'),
    (r'\bTime\b', 'Equipo'),
    (r'\bvendedor\b', 'vendedor'),
    (r'\bvendedores\b', 'vendedores'),
    (r'\btambém pode\b', 'también puede'),
    (r'\bpor produto\b', 'por producto'),
    (r'\bdaí\b', 'desde ahí'),
    (r'\bpartir\b', 'partir'),
    (r'\bdeve ser\b', 'debe ser'),
    (r'\bpodem ser\b', 'pueden ser'),
    (r'\bdevem ser\b', 'deben ser'),
    (r'\bse fizer\b', 'si hace'),
    (r'\bfizer\b', 'hace'),
    (r'\bfazendo\b', 'haciendo'),
    (r'\bsendo\b', 'siendo'),
    (r'\btendo\b', 'teniendo'),
]

ALL = [(re.compile(p), r) for p, r in (P8 + EXTRA)]

def translate_file(path: pathlib.Path) -> bool:
    try:
        text = path.read_text(encoding='utf-8')
    except Exception:
        return False
    orig = text
    for pat, repl in ALL:
        text = pat.sub(repl, text)
    if text != orig:
        path.write_text(text, encoding='utf-8')
        return True
    return False

def main():
    roots = [
        pathlib.Path('src/components/admin'),
        pathlib.Path('src/hooks'),
        pathlib.Path('src/pages'),
        pathlib.Path('src/components/lead'),
        pathlib.Path('src/components/seller'),
        pathlib.Path('src/components/brain'),
        pathlib.Path('src/components/objections'),
        pathlib.Path('src/components/calendar'),
        pathlib.Path('src/components/cadence'),
        pathlib.Path('src/components/insights'),
        pathlib.Path('src/components/materials'),
        pathlib.Path('src/components/notifications'),
        pathlib.Path('src/components/onboarding'),
        pathlib.Path('src/components/playbook'),
        pathlib.Path('src/components/product'),
        pathlib.Path('src/components/quiz'),
        pathlib.Path('src/components/search'),
        pathlib.Path('src/components/tasks'),
        pathlib.Path('src/components/dashboard'),
        pathlib.Path('src/components/inbox'),
        pathlib.Path('src/components/mobile'),
        pathlib.Path('src/components/layout'),
        pathlib.Path('src/components/auth'),
        pathlib.Path('src/components/superadmin'),
        pathlib.Path('supabase/migrations_shared'),
    ]
    exts = {'.tsx', '.ts', '.sql'}
    count = 0
    for root in roots:
        if not root.exists():
            continue
        for p in root.rglob('*'):
            if p.suffix not in exts:
                continue
            if translate_file(p):
                count += 1
    print(f"Total: {count} archivos editados")

if __name__ == '__main__':
    main()
