"""Phase 6 — translate Portuguese system messages in hooks/ to Spanish."""
import os, re

# Global pattern-based replacements applied to all src/hooks/*.ts files
GLOBAL = [
    # Generic patterns
    ("Erro ao atualizar ", "Error al actualizar "),
    ("Erro ao criar ", "Error al crear "),
    ("Erro ao excluir ", "Error al eliminar "),
    ("Erro ao remover ", "Error al eliminar "),
    ("Erro ao salvar ", "Error al guardar "),
    ("Erro ao duplicar ", "Error al duplicar "),
    ("Erro ao enviar ", "Error al enviar "),
    ("Erro ao alterar ", "Error al cambiar "),
    ("Erro ao conectar:", "Error al conectar:"),
    ("Erro ao conectar", "Error al conectar"),
    ("Erro ao desconectar:", "Error al desconectar:"),
    ("Erro ao desconectar", "Error al desconectar"),
    ("Erro ao gerar ", "Error al generar "),
    ("Erro ao otimizar com IA", "Error al optimizar con IA"),
    ("Erro ao aplicar ", "Error al aplicar "),
    ("Erro ao atribuir ", "Error al asignar "),
    ("Erro ao assumir ", "Error al asumir "),
    ("Erro ao cancelar ", "Error al cancelar "),
    ("Erro ao concluir ", "Error al concluir "),
    ("Erro ao reagendar", "Error al reagendar"),
    ("Erro ao adicionar ", "Error al añadir "),
    ("Erro ao fazer upload", "Error al subir el archivo"),
    ("Erro ao processar ", "Error al procesar "),
    ("Erro ao transcrever áudio", "Error al transcribir audio"),
    ("Erro ao pausar sessão:", "Error al pausar sesión:"),
    ("Erro ao renomear:", "Error al renombrar:"),
    ("Erro ao sincronizar:", "Error al sincronizar:"),
    ("Erro ao desvincular:", "Error al desvincular:"),
    ("Erro ao atrelar:", "Error al vincular:"),
    ("Erro na sincronização:", "Error en la sincronización:"),
    ("Erro na sync:", "Error en sync:"),
    ("Erro:", "Error:"),
    ("Falha ao salvar", "Error al guardar"),
    ("Falha ao gerar URL de autorização", "Error al generar URL de autorización"),
    ("Falha na importação", "Error en la importación"),
    ("Falha na sincronização", "Error en la sincronización"),
    ("Falha:", "Error:"),

    ("com sucesso!", "con éxito!"),
    ("com sucesso.", "con éxito."),
    ("com sucesso", "con éxito"),
    (" criado!", " creado!"),
    (" criada!", " creada!"),
    (" criado", " creado"),
    (" criada", " creada"),
    (" atualizado!", " actualizado!"),
    (" atualizada!", " actualizada!"),
    (" atualizado", " actualizado"),
    (" atualizada", " actualizada"),
    (" removido!", " eliminado!"),
    (" removida!", " eliminada!"),
    (" removido", " eliminado"),
    (" removida", " eliminada"),
    (" excluído!", " eliminado!"),
    (" excluída!", " eliminada!"),
    (" excluído", " eliminado"),
    (" excluída", " eliminada"),
    (" salvo!", " guardado!"),
    (" salva!", " guardada!"),
    (" salvo", " guardado"),
    (" salva", " guardada"),
    (" enviado!", " enviado!"),
    (" enviada!", " enviada!"),
    (" duplicado!", " duplicado!"),
    (" alterado", " cambiado"),
    (" aplicado", " aplicado"),

    # Common nouns / phrases
    ("Organização não encontrada", "Organización no encontrada"),
    ("organização não encontrada", "organización no encontrada"),
    ("Sem organização", "Sin organización"),
    ("sem organização", "sin organización"),
    ("Sem usuário", "Sin usuario"),
    ("Usuário não autenticado", "Usuario no autenticado"),
    ("Configurações", "Ajustes"),
    ("Configuração", "Configuración"),
    ("Conexão", "Conexión"),
    ("conexão", "conexión"),
    ("Integração", "Integración"),
    ("Notificações", "Notificaciones"),
    ("Notificação", "Notificación"),
    ("Automação", "Automatización"),
    ("Automações", "Automatizaciones"),
    ("Mapeamento", "Mapeo"),
    ("Função", "Rol"),
    ("Conteúdo da mensagem", "Contenido del mensaje"),
    ("Nome da organização", "Nombre de la organización"),
    ("Nome do usuário", "Nombre del usuario"),
    ("Título do comunicado", "Título del comunicado"),
    ("Tente novamente", "Intentá de nuevo"),
    ("não foi possível", "no fue posible"),
    ("Não foi possível", "No fue posible"),
    ("Não é possível", "No es posible"),

    # Specific domain
    ("Agendamento cancelado!", "¡Reserva cancelada!"),
    ("Agendamento cancelado", "Reserva cancelada"),
    ("Agendamento concluído!", "¡Reserva completada!"),
    ("Agendamento reagendado", "Reserva reprogramada"),
    ("Agendamento confirmado!", "¡Reserva confirmada!"),
    ("Agendamento removido", "Reserva eliminada"),
    ("Agendamento salvo", "Reserva guardada"),
    ("Erro ao cancelar agendamento", "Error al cancelar la reserva"),
    ("Erro ao concluir agendamento", "Error al completar la reserva"),

    ("Tipo de evento", "Tipo de evento"),
    ("Nenhum evento novo para sincronizar", "No hay eventos nuevos para sincronizar"),
    ("Evento criado", "Evento creado"),
    ("Evento atualizado", "Evento actualizado"),
    ("Erro ao atualizar evento", "Error al actualizar el evento"),
    ("Erro ao criar evento", "Error al crear el evento"),
    ("Erro ao excluir evento", "Error al eliminar el evento"),
    ("As alterações foram salvas.", "Los cambios fueron guardados."),
    ("O evento foi removido da agenda.", "El evento fue eliminado de la agenda."),
    ("O evento foi adicionado à agenda.", "El evento fue añadido a la agenda."),

    ("Fluxo ", "Flujo "),
    ("Funil ", "Embudo "),
    ("Formulário ", "Formulario "),
    ("formulário ", "formulario "),
    ("funil ", "embudo "),
    ("fluxo ", "flujo "),

    ("Squad atualizado!", "¡Squad actualizado!"),
    ("Squad criado", "Squad creado"),
    ("Squad removido!", "¡Squad eliminado!"),
    ("Membro removido do squad!", "¡Miembro eliminado del squad!"),
    ("Membro adicionado ao squad!", "¡Miembro añadido al squad!"),
    ("Este membro já está no squad", "Este miembro ya está en el squad"),
    ("Erro ao adicionar membro", "Error al añadir miembro"),
    ("Erro ao remover membro", "Error al eliminar miembro"),
    ("Erro ao atualizar squad", "Error al actualizar squad"),
    ("Erro ao criar squad", "Error al crear squad"),
    ("Erro ao remover squad", "Error al eliminar squad"),
    ("Erro ao atualizar função", "Error al actualizar rol"),
    ("Função atualizada!", "¡Rol actualizado!"),
    ("Erro ao fazer upload da imagem", "Error al subir la imagen"),
    ("Erro ao fazer upload da foto", "Error al subir la foto"),

    ("Já existe um contato com este telefone nesta organização.",
     "Ya existe un contacto con este teléfono en esta organización."),
    ("Já existe um campo com essa chave",
     "Ya existe un campo con esa clave"),
    ("Já existe um convite pe", "Ya existe una invitación pe"),

    ("Lead criado", "Lead creado"),
    ("Leads excluídos", "Leads eliminados"),
    ("Leads transferidos", "Leads transferidos"),
    ("🎯 Lead assumido com sucesso!", "🎯 ¡Lead asumido con éxito!"),
    ("🎯 Lead assumido!", "🎯 ¡Lead asumido!"),
    ("🎯 Lead pendente atribuído a você!", "🎯 ¡Lead pendiente asignado a vos!"),
    ("O lead foi adicionado ao seu pipeline.", "El lead fue añadido a tu pipeline."),
    ("Nenhum lead pendente na fila do squad.", "No hay leads pendientes en la cola del squad."),
    ("Erro ao assumir lead. Tente novamente.", "Error al asumir lead. Intentá de nuevo."),
    ("Erro ao assumir lead", "Error al asumir lead"),

    ("Conexão criada! Escaneie o QR Code para ativar.",
     "¡Conexión creada! Escaneá el QR Code para activar."),
    ("Sessão pausada. Reconecte quando quiser — o número fica salvo.",
     "Sesión pausada. Reconectá cuando quieras — el número queda guardado."),
    ("Nenhuma instância encontrada no servidor.",
     "Ninguna instancia encontrada en el servidor."),
    ("Instância criada", "Instancia creada"),
    ("Instância removida", "Instancia eliminada"),
    ("Instância padrão definida", "Instancia predeterminada establecida"),
    ("Instância atrelada à empresa", "Instancia vinculada a la empresa"),
    ("Webhook configurado", "Webhook configurado"),
    ("Configuração do servidor salva", "Configuración del servidor guardada"),
    ("WhatsApp desvinculado. Escaneie um novo QR para conectar outro número.",
     "WhatsApp desvinculado. Escaneá un nuevo QR para conectar otro número."),

    ("Negociando termos e condições", "Negociando términos y condiciones"),
    ("Negócio fechado com sucesso", "Negocio cerrado con éxito"),
    ("Negócio", "Negocio"),
    ("negócio", "negocio"),
    ("Primeiro contato com o cliente potencial", "Primer contacto con el cliente potencial"),
    ("Proposta comercial enviada", "Propuesta comercial enviada"),

    ("Verifique sua caixa de entrada para confirmar a alteração.",
     "Revisá tu casilla de entrada para confirmar el cambio."),
    ("Email de confirmação enviado!", "¡Correo de confirmación enviado!"),
    ("Perfil atualizado", "Perfil actualizado"),
    ("Senha atualizada", "Contraseña actualizada"),
    ("Erro ao atualizar email", "Error al actualizar el correo"),
    ("Erro ao atualizar perfil", "Error al actualizar el perfil"),
    ("Erro ao atualizar senha", "Error al actualizar la contraseña"),

    ("Conexão com Sankhya estabelecida com sucesso!", "¡Conexión con Sankhya establecida con éxito!"),
    ("Configurações do Sankhya salvas", "Ajustes de Sankhya guardados"),
    ("Sincronização de ", "Sincronización de "),
    (" iniciada", " iniciada"),

    ("Hotmart OK", "Hotmart OK"),
    ("Conexão Hotmart OK", "Conexión Hotmart OK"),

    ("Conexão Instagram ativa", "Conexión de Instagram activa"),

    ("Cadastre a primeira organização cliente.", "Registrá la primera organización cliente."),
    ("Configuração inicial concluída!", "¡Configuración inicial completada!"),
    ("Erro ao concluir configuração", "Error al completar la configuración"),
    ("Substitua a senha de instalação por uma senha forte.",
     "Sustituí la contraseña de instalación por una contraseña fuerte."),

    ("Pacote gerado: ", "Paquete generado: "),
    (" etiquetas + ", " etiquetas + "),
    (" automações ativas.", " automatizaciones activas."),

    ("Executar ação do dia ", "Ejecutar acción del día "),
    (" da cadência para ", " de la cadencia para "),

    ("Análise iniciada — acompanhe o progresso em tempo real",
     "Análisis iniciado — seguí el progreso en tiempo real"),

    ("Notificação enviada para ", "Notificación enviada a "),
    (" destinatário(s)", " destinatario(s)"),
    ("Nenhum destinatário encontrado para o escopo selecionado",
     "Ningún destinatario encontrado para el ámbito seleccionado"),

    ("Mensagem enviada via ", "Mensaje enviado vía "),
    ("Nenhuma conexão WhatsApp cadastrada para esta empresa",
     "Ninguna conexión WhatsApp registrada para esta empresa"),

    ("Lidar com cancelamento e tentativa de retenção",
     "Gestionar cancelación e intento de retención"),
    ("Disputa de pagamento iniciada", "Disputa de pago iniciada"),
    ("Pagamento confirmado, entregar acesso", "Pago confirmado, entregar acceso"),
    ("Recuperar checkout não finalizado", "Recuperar checkout no finalizado"),

    ("Ação removida", "Acción eliminada"),
    ("Ação salva", "Acción guardada"),
    ("Erro ao remover:", "Error al eliminar:"),
    ("Erro ao salvar:", "Error al guardar:"),
    ("Erro ao remover", "Error al eliminar"),
    ("Erro ao salvar", "Error al guardar"),

    ("Chave removida", "Clave eliminada"),
    ("Chave verificada com sucesso", "Clave verificada con éxito"),
    ("Chave verificada e salva", "Clave verificada y guardada"),
    ("Chave salva e verificada", "Clave guardada y verificada"),

    ("Especialista removido", "Especialista eliminado"),
    ("Especialista salvo", "Especialista guardado"),
    ("Regra removida", "Regla eliminada"),
    ("Regra salva", "Regla guardada"),

    ("Experimento removido", "Experimento eliminado"),
    ("Experimento salvo", "Experimento guardado"),
    ("Variante removida", "Variante eliminada"),
    ("Variante salva", "Variante guardada"),

    ("Template criado", "Plantilla creada"),
    ("Template atualizado", "Plantilla actualizada"),
    ("Template excluído", "Plantilla eliminada"),
    ("Template removido", "Plantilla eliminada"),
    ("Template salvo", "Plantilla guardada"),
    ("Template salvo com sucesso", "Plantilla guardada con éxito"),
    ("Template enviado para aprovação", "Plantilla enviada para aprobación"),

    ("Campo atualizado", "Campo actualizado"),
    ("Campo criado", "Campo creado"),
    ("Campo removido", "Campo eliminado"),
    ("Erro ao atualizar campo", "Error al actualizar el campo"),
    ("Erro ao criar campo", "Error al crear el campo"),
    ("Erro ao remover campo", "Error al eliminar el campo"),

    ("Item atualizado", "Ítem actualizado"),
    ("Item removido", "Ítem eliminado"),
    ("Importação concluída", "Importación completada"),
    ("Sincronização concluída", "Sincronización completada"),

    ("Conexão renomeada", "Conexión renombrada"),
    ("Conexão excluída", "Conexión eliminada"),
    ("Conexão removida", "Conexión eliminada"),
    ("Conexão salva", "Conexión guardada"),
    ("Conexão validada", "Conexión validada"),

    ("Automação removida", "Automatización eliminada"),
    ("Automação salva", "Automatización guardada"),
    ("Etiqueta atualizada", "Etiqueta actualizada"),
    ("Etiqueta criada", "Etiqueta creada"),
    ("Etiqueta removida", "Etiqueta eliminada"),
    ("Erro ao aplicar etiqueta", "Error al aplicar la etiqueta"),
    ("Erro ao criar etiqueta", "Error al crear la etiqueta"),

    ("Campanha atualizada", "Campaña actualizada"),
    ("Campanha criada", "Campaña creada"),
    ("Campanha enviada", "Campaña enviada"),
    ("Campanha excluída", "Campaña eliminada"),

    ("CTA atualizado!", "¡CTA actualizado!"),
    ("CTA criado", "CTA creado"),
    ("CTA removido!", "¡CTA eliminado!"),
    ("Erro ao atualizar CTA", "Error al actualizar el CTA"),
    ("Erro ao criar CTA", "Error al crear el CTA"),
    ("Erro ao remover CTA", "Error al eliminar el CTA"),

    ("Agente atualizado", "Agente actualizado"),
    ("Agente criado", "Agente creado"),
    ("Agente excluído", "Agente eliminado"),
    ("Agente definido como padrão!", "¡Agente establecido como predeterminado!"),
    ("Agente gerado", "Agente generado"),
    ("Erro ao atualizar agente", "Error al actualizar el agente"),
    ("Erro ao criar agente", "Error al crear el agente"),
    ("Erro ao excluir agente", "Error al eliminar el agente"),
    ("Erro ao definir agente padrão", "Error al definir agente predeterminado"),
    ("Erro ao alterar status do agente", "Error al cambiar el estado del agente"),

    ("Dia atualizado!", "¡Día actualizado!"),
    ("Dia criado", "Día creado"),
    ("Dia removido!", "¡Día eliminado!"),
    ("Erro ao atualizar dia", "Error al actualizar el día"),
    ("Erro ao criar dia", "Error al crear el día"),
    ("Erro ao remover dia", "Error al eliminar el día"),

    ("Etapa atualizada!", "¡Etapa actualizada!"),
    ("Etapa criada!", "¡Etapa creada!"),
    ("Etapa removida!", "¡Etapa eliminada!"),
    ("Erro ao atualizar etapa", "Error al actualizar la etapa"),
    ("Erro ao criar etapa", "Error al crear la etapa"),
    ("Erro ao remover etapa", "Error al eliminar la etapa"),

    ("Produto criado com sucesso!", "¡Producto creado con éxito!"),
    ("Erro ao criar produto", "Error al crear el producto"),

    ("Comissão aprovada", "Comisión aprobada"),
    ("Comissão marcada como paga", "Comisión marcada como pagada"),

    ("Configurações atualizadas", "Ajustes actualizados"),
    ("Configurações salvas", "Ajustes guardados"),
    ("Erro ao atualizar configurações", "Error al actualizar los ajustes"),
    ("Erro ao salvar configurações", "Error al guardar los ajustes"),
    ("Erro ao salvar configuração", "Error al guardar la configuración"),
    ("Configuração salva", "Configuración guardada"),

    ("Configurações de email salvas", "Ajustes de correo guardados"),

    ("Erro ao atualizar status", "Error al actualizar el estado"),
    ("Erro ao alterar status:", "Error al cambiar el estado:"),
    ("Erro ao alterar status do evento", "Error al cambiar el estado del evento"),

    ("Erro ao enviar", "Error al enviar"),

    ("Pedidos", "Pedidos"),
    ("Roteamento", "Enrutamiento"),

    # Common verbs/words that may still leak
    ("Sucesso!", "¡Éxito!"),
    ("Sucesso", "Éxito"),
    ("Aguarde", "Espera"),
    ("aguarde", "espera"),
    ("Próximo", "Siguiente"),
    ("próximo", "siguiente"),
    ("Próxima", "Siguiente"),
    ("Última", "Última"),
    ("Último", "Último"),
    ("Carregando...", "Cargando..."),
    ("Carregando…", "Cargando…"),
    ("Carregando", "Cargando"),

    ("Falha ao salvar roteamento:", "Error al guardar enrutamiento:"),
    ("Falha ao salvar:", "Error al guardar:"),
]

count = 0
for root, _, files in os.walk('src/hooks'):
    for f in files:
        if not f.endswith(('.ts','.tsx')): continue
        path = os.path.join(root, f)
        with open(path) as fh:
            original = fh.read()
        content = original
        for old, new in GLOBAL:
            content = content.replace(old, new)
        if content != original:
            with open(path, 'w') as fh:
                fh.write(content)
            count += 1
            print(f"updated: {path}")
print(f"\n{count} files updated")
