#!/usr/bin/env python3
"""Fase 9.b: residuos finales PT-BR en edge functions."""
import re, pathlib

# Phrase-level (longest first to avoid partial overlaps)
PHRASES = [
    # Big phrases
    ('ANALISE TODO o histórico da conversación', 'ANALIZÁ TODO el historial de la conversación'),
    ('siga estas regras', 'seguí estas reglas'),
    ('Cada mensaje DEVE progredir a conversación', 'Cada mensaje DEBE hacer avanzar la conversación'),
    ('nunca voltar a um ponto já coberto', 'nunca volver a un punto ya cubierto'),
    ('Qualquer frase que já apareceu no histórico desta conversación', 'Cualquier frase que ya apareció en el historial de esta conversación'),
    ('Quanto tempo vocês dedicam a', 'Cuánto tiempo dedican a'),
    ('por semana', 'por semana'),
    ('Qual o maior gargalo que vocês enfrentam com isso', 'Cuál es el mayor cuello de botella que enfrentan con eso'),
    ('Quanto vocês estimam que perdem por causa disso', 'Cuánto estiman que pierden por eso'),
    ('No liste features', 'No enumeres features'),
    ('mostre como resolve a DOR específica que ele mencionou', 'mostrá cómo resuelve el DOLOR específico que mencionó'),
    ('Usa o NOME del cliente quando souber', 'Usá el NOMBRE del cliente cuando lo sepas'),
    ('mas no em toda mensaje', 'pero no en cada mensaje'),
    ('Fale como humano', 'Hablá como humano'),
    ('linguagem natural do día-a-día', 'lenguaje natural del día a día'),
    ('Ignorar o que já fue discutido/combinado na conversación', 'Ignorar lo que ya fue discutido/acordado en la conversación'),
    ('Agente no encontrado para o teste', 'Agente no encontrado para la prueba'),
    ('Roteamento concluído para', 'Ruteo completado a'),
    ('Em produção, a partir daqui o lead conversaria diretamente com este agente', 'En producción, desde aquí el lead conversaría directamente con este agente'),
    ('Iniciaria o flujo configurado para a opción', 'Iniciaría el flujo configurado para la opción'),
    ('A conversación já fue roteada para', 'La conversación ya fue ruteada a'),
    ('nesta sessão de teste', 'en esta sesión de prueba'),
    ('Clique em "Limpar" para reiniciar o flujo do orquestrador', 'Hacé clic en "Limpiar" para reiniciar el flujo del orquestador'),
    ('Clique em "Limpar" para reiniciar', 'Hacé clic en "Limpiar" para reiniciar'),
    ('já fue encaminhada para humano', 'ya fue derivada a humano'),
    ('do histórico', 'del historial'),
    ('do orquestrador', 'del orquestador'),
    ('da conversación', 'de la conversación'),
    ('na conversación', 'en la conversación'),
    ('a conversación', 'la conversación'),
    ('A conversación', 'La conversación'),
    ('o flujo', 'el flujo'),
    ('o lead', 'el lead'),
    ('o teste', 'la prueba'),
    ('para o teste', 'para la prueba'),
    ('para a opción', 'para la opción'),
    ('a opción', 'la opción'),
    ('A opción', 'La opción'),
    ('do día', 'del día'),
    ('no día', 'en el día'),
    ('día-a-día', 'día a día'),
    ('em toda', 'en cada'),
    ('Em produção', 'En producción'),
    ('em produção', 'en producción'),
    ('a partir daqui', 'desde aquí'),
    ('a partir de', 'a partir de'),
    ('é necessário', 'es necesario'),
    ('foi enviada', 'fue enviada'),
    ('foi enviado', 'fue enviado'),
    ('foi recebida', 'fue recibida'),
    ('foi recebido', 'fue recibido'),
    ('foi criado', 'fue creado'),
    ('foi criada', 'fue creada'),
    ('foi atualizado', 'fue actualizado'),
    ('foi atualizada', 'fue actualizada'),
    ('foi excluído', 'fue eliminado'),
    ('foi excluída', 'fue eliminada'),
    ('foi feito', 'fue hecho'),
    ('foi feita', 'fue hecha'),
    ('está disponível', 'está disponible'),
    ('não disponível', 'no disponible'),
    ('disponível', 'disponible'),
    ('Disponível', 'Disponible'),
    ('indisponível', 'no disponible'),
    ('possível', 'posible'),
    ('Possível', 'Posible'),
    ('impossível', 'imposible'),
    ('através', 'a través'),
    ('através de', 'a través de'),
    ('Através', 'A través'),
    ('estão', 'están'),
    ('Estão', 'Están'),
    ('Já fue', 'Ya fue'),
    ('já fue', 'ya fue'),
    ('vocês', 'ustedes'),
    ('Vocês', 'Ustedes'),
]

# Word-level (case-sensitive, word-boundary)
WORDS = [
    (r'\bVocê é\b', 'Sos'),
    (r'\bvocê é\b', 'sos'),
    (r'\bVocê está\b', 'Estás'),
    (r'\bvocê está\b', 'estás'),
    (r'\bVocê tem\b', 'Tenés'),
    (r'\bvocê tem\b', 'tenés'),
    (r'\bVocê deve\b', 'Debés'),
    (r'\bvocê deve\b', 'debés'),
    (r'\bVocê pode\b', 'Podés'),
    (r'\bvocê pode\b', 'podés'),
    (r'\bVocê\b', 'Vos'),
    (r'\bvocê\b', 'vos'),
    (r'\bnão\b', 'no'),
    (r'\bNão\b', 'No'),
    (r'\bSeu\b', 'Su'),
    (r'\bseu\b', 'su'),
    (r'\bSua\b', 'Su'),
    (r'\bsua\b', 'su'),
    (r'\bSeus\b', 'Sus'),
    (r'\bseus\b', 'sus'),
    (r'\btambém\b', 'también'),
    (r'\bTambém\b', 'También'),
    (r'\bporém\b', 'pero'),
    (r'\bPorém\b', 'Pero'),
    (r'\bonde\b', 'donde'),
    (r'\bOnde\b', 'Dónde'),
    (r'\bquando\b', 'cuando'),
    (r'\bQuando\b', 'Cuando'),
    (r'\bporque\b', 'porque'),
    (r'\bagora\b', 'ahora'),
    (r'\bAgora\b', 'Ahora'),
    (r'\bagora mismo\b', 'ahora mismo'),
    (r'\bsempre\b', 'siempre'),
    (r'\bnunca\b', 'nunca'),
    (r'\btodos\b', 'todos'),
    (r'\bTodos\b', 'Todos'),
    (r'\btodas\b', 'todas'),
    (r'\bmuito\b', 'mucho'),
    (r'\bMuito\b', 'Mucho'),
    (r'\bmuitos\b', 'muchos'),
    (r'\bmuitas\b', 'muchas'),
    (r'\bdesde\b', 'desde'),
    (r'\bdesta\b', 'de esta'),
    (r'\bdeste\b', 'de este'),
    (r'\bnesta\b', 'en esta'),
    (r'\bneste\b', 'en este'),
    (r'\bnessa\b', 'en esa'),
    (r'\bnesse\b', 'en ese'),
    (r'\bcomo\b', 'como'),
    (r'\bComo\b', 'Cómo'),
    (r'\bobrigatórios\b', 'obligatorios'),
    (r'\bobrigatório\b', 'obligatorio'),
    (r'\bobrigatórias\b', 'obligatorias'),
    (r'\bobrigatória\b', 'obligatoria'),
    (r'\bcadastro\b', 'registro'),
    (r'\bCadastro\b', 'Registro'),
    (r'\bcadastrar\b', 'registrar'),
    (r'\bcadastrado\b', 'registrado'),
    (r'\bcadastrada\b', 'registrada'),
    (r'\bagendamento\b', 'reserva'),
    (r'\bAgendamento\b', 'Reserva'),
    (r'\bagendamentos\b', 'reservas'),
    (r'\bmensagem\b', 'mensaje'),
    (r'\bMensagem\b', 'Mensaje'),
    (r'\bmensagens\b', 'mensajes'),
    (r'\bconversa\b', 'conversación'),
    (r'\bConversa\b', 'Conversación'),
    (r'\bvendedor\b', 'vendedor'),
    (r'\bvenda\b', 'venta'),
    (r'\bvendas\b', 'ventas'),
    (r'\bVenda\b', 'Venta'),
    (r'\bcriação\b', 'creación'),
    (r'\bCriação\b', 'Creación'),
    (r'\bcriado\b', 'creado'),
    (r'\bcriada\b', 'creada'),
    (r'\bação\b', 'acción'),
    (r'\bAção\b', 'Acción'),
    (r'\bações\b', 'acciones'),
    (r'\bAções\b', 'Acciones'),
    (r'\batenção\b', 'atención'),
    (r'\bAtenção\b', 'Atención'),
    (r'\busuário\b', 'usuario'),
    (r'\bUsuário\b', 'Usuario'),
    (r'\busuários\b', 'usuarios'),
    (r'\bendereço\b', 'dirección'),
    (r'\bEndereço\b', 'Dirección'),
    (r'\btelefone\b', 'teléfono'),
    (r'\bTelefone\b', 'Teléfono'),
    (r'\bobrigado\b', 'gracias'),
    (r'\bObrigado\b', 'Gracias'),
    (r'\bportuguês\b', 'español'),
    (r'\bPortuguês\b', 'Español'),
    (r'\bcomeçar\b', 'comenzar'),
    (r'\bComeçar\b', 'Comenzar'),
    (r'\bcomeço\b', 'comienzo'),
    (r'\bComeço\b', 'Comienzo'),
    (r'\bfazer\b', 'hacer'),
    (r'\bFazer\b', 'Hacer'),
    (r'\bfeito\b', 'hecho'),
    (r'\bfeita\b', 'hecha'),
    (r'\bsido\b', 'sido'),
    (r'\bestá\b', 'está'),
    (r'\bsão\b', 'son'),
    (r'\bSão\b', 'Son'),
    (r'\bpara o\b', 'para el'),
    (r'\bpara a\b', 'para la'),
    (r'\bpara os\b', 'para los'),
    (r'\bpara as\b', 'para las'),
    (r'\bao cliente\b', 'al cliente'),
    (r'\bao usuário\b', 'al usuario'),
    (r'\bao lead\b', 'al lead'),
    (r'\bao agente\b', 'al agente'),
    (r'\bdo cliente\b', 'del cliente'),
    (r'\bda empresa\b', 'de la empresa'),
    (r'\bdo produto\b', 'del producto'),
    (r'\bdo agente\b', 'del agente'),
    (r'\bdo lead\b', 'del lead'),
    (r'\bdo usuário\b', 'del usuario'),
    (r'\bteste\b', 'prueba'),
    (r'\bTeste\b', 'Prueba'),
    (r'\bdo día\b', 'del día'),
    (r'\bno día\b', 'en el día'),
    (r'\bopção\b', 'opción'),
    (r'\bOpção\b', 'Opción'),
    (r'\bopções\b', 'opciones'),
    (r'\bOpções\b', 'Opciones'),
    (r'\bnúmero\b', 'número'),
    (r'\bNúmero\b', 'Número'),
    (r'\bjá\b', 'ya'),
    (r'\bJá\b', 'Ya'),
    (r'\baté\b', 'hasta'),
    (r'\bAté\b', 'Hasta'),
    (r'\bainda\b', 'aún'),
    (r'\bAinda\b', 'Aún'),
    (r'\bapenas\b', 'solo'),
    (r'\bApenas\b', 'Solo'),
    (r'\bquase\b', 'casi'),
    (r'\bQuase\b', 'Casi'),
    (r'\bquer\b', 'quiere'),
    (r'\bquero\b', 'quiero'),
    (r'\btenho\b', 'tengo'),
    (r'\btenha\b', 'tenga'),
    (r'\btivemos\b', 'tuvimos'),
    (r'\bteremos\b', 'tendremos'),
    (r'\bvai\b', 'va'),
    (r'\bvão\b', 'van'),
]

# Identifier protection: skip lines that look like pure code (no string quotes)
# Heuristic: only apply WORDS to lines that contain a quote/backtick/comment
QUOTE_CHARS = ('"', "'", '`', '//', '/*')

def has_text_context(line: str) -> bool:
    return any(q in line for q in QUOTE_CHARS)

phrase_pats = [(p, r) for p, r in PHRASES]
word_pats = [(re.compile(p), r) for p, r in WORDS]

def translate(text: str) -> str:
    # Phrase pass: line-by-line (safer)
    out_lines = []
    for line in text.split('\n'):
        if has_text_context(line):
            for p, r in phrase_pats:
                if p in line:
                    line = line.replace(p, r)
            for pat, repl in word_pats:
                line = pat.sub(repl, line)
        out_lines.append(line)
    return '\n'.join(out_lines)

def main():
    root = pathlib.Path('supabase/functions')
    count = 0
    for p in root.rglob('*.ts'):
        skip = ('email-templates','transactional-email-templates',
                'agent-prompt-templates','booking-templates','quick-menu')
        if any(s in str(p) for s in skip):
            continue
        try: text = p.read_text(encoding='utf-8')
        except: continue
        new = translate(text)
        if new != text:
            p.write_text(new, encoding='utf-8')
            count += 1
    print(f'edited: {count}')

if __name__ == '__main__':
    main()
